USE HR;

#QUESTION 1
#Q.no(1).Maximum quantity of which product, other than the promotional product, (whose id starts with 9999) fits in a given carton (say, carton id 10).
SELECT PRODUCT_ID, PRODUCT_DESC, PRODUCT_QUANTITY_AVAIL
FROM (SELECT *
FROM
(SELECT PRODUCT_ID,PRODUCT_DESC, PRODUCT_QUANTITY_AVAIL, CARTON_ID, (P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY_AVAIL) AS PROD_VOL, (C.LEN*C.WIDTH*C.HEIGHT) AS CART_VOL,
(CASE
     WHEN ((P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY_AVAIL) <= (C.LEN*C.WIDTH*C.HEIGHT)) THEN '1'
     ELSE '0'
END) AS FITTING
FROM PRODUCT P CROSS JOIN CARTON C
WHERE PRODUCT_ID NOT LIKE ('%999%') AND CARTON_ID = 10) AS A
WHERE FITTING = 1) AS C
WHERE PRODUCT_QUANTITY_AVAIL =(SELECT MAX(PRODUCT_QUANTITY_AVAIL)
FROM (SELECT *
FROM
(SELECT PRODUCT_ID,PRODUCT_DESC, PRODUCT_QUANTITY_AVAIL, CARTON_ID, (P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY_AVAIL) AS PROD_VOL, (C.LEN*C.WIDTH*C.HEIGHT) AS CART_VOL,
(CASE
     WHEN ((P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY_AVAIL) <= (C.LEN*C.WIDTH*C.HEIGHT)) THEN '1'
     ELSE '0'
END) AS FITTING
FROM PRODUCT P CROSS JOIN CARTON C
WHERE PRODUCT_ID NOT LIKE ('%999%') AND CARTON_ID = 10) AS A
WHERE FITTING = 1) AS B);



#QUESTION 2
#Q.no(2).Which class of products have been shipped highest, to countries outside India other than USA? Also show the total value of those items.
SELECT * FROM (SELECT PRODUCT_CLASS_CODE, SUM(PRODUCT_QUANTITY) AS TOT
FROM PRODUCT P 
NATURAL JOIN ORDER_ITEMS OI 
NATURAL JOIN ORDER_HEADER OH 
NATURAL JOIN ONLINE_CUSTOMER OC 
NATURAL JOIN ADDRESS A 
WHERE COUNTRY NOT IN ('India','USA')
GROUP BY PRODUCT_CLASS_CODE) AS A
WHERE TOT IN(SELECT MAX(TOT) FROM (SELECT PRODUCT_CLASS_CODE, SUM(PRODUCT_QUANTITY) AS TOT
FROM PRODUCT P 
NATURAL JOIN ORDER_ITEMS OI 
NATURAL JOIN ORDER_HEADER OH 
NATURAL JOIN ONLINE_CUSTOMER OC 
NATURAL JOIN ADDRESS A 
WHERE COUNTRY NOT IN ('India','USA')
GROUP BY PRODUCT_CLASS_CODE)AS A);

#QUESTION 3
#Q.no(3).Show product id, description and price of products that have the same price, other than the promotional products.
SELECT P2.PRODUCT_ID,P2.PRODUCT_DESC, P1.PRODUCT_ID, P1.PRODUCT_DESC, P1.PRODUCT_PRICE
FROM PRODUCT P1, PRODUCT P2
WHERE P1.PRODUCT_PRICE = P2.PRODUCT_PRICE AND P1.PRODUCT_ID!=P2.PRODUCT_ID AND P1.PRODUCT_ID NOT LIKE ('%999%');

#QUESTION 4
#FOR SPECIFICALLY RPODUCT_ID 212
#Q.no(4).For a given item, which item has been bought along with it, maximum no. of times.
SELECT A.PRODUCT_ID, PRODUCT_DESC, PRODUCT_QUANTITY
FROM (SELECT PRODUCT_ID, PRODUCT_QUANTITY
FROM ORDER_ITEMS
WHERE PRODUCT_ID NOT IN (212) 
AND ORDER_ID IN (SELECT ORDER_ID FROM ORDER_ITEMS WHERE PRODUCT_ID = 212)) AS A
JOIN PRODUCT P ON A.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCT_QUANTITY IN (SELECT MAX(PRODUCT_QUANTITY)
FROM ORDER_ITEMS
WHERE PRODUCT_ID NOT IN (212) 
AND ORDER_ID IN (SELECT ORDER_ID FROM ORDER_ITEMS WHERE PRODUCT_ID = 212));


#QUESTION 6
#Q.no(6).During which month of the year do foreign customers tend to buy max. no. of products.
SELECT MONTH_
FROM (SELECT MONTH(ORDER_DATE) AS MONTH_, SUM(PRODUCT_QUANTITY) AS TOT_ITEMS
FROM ONLINE_CUSTOMER OC
JOIN ORDER_HEADER OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
JOIN ORDER_ITEMS OI ON OI.ORDER_ID = OH.ORDER_ID
JOIN ADDRESS A ON OC.ADDRESS_ID = A.ADDRESS_ID
WHERE COUNTRY NOT LIKE 'India'
GROUP BY MONTH(ORDER_DATE)
)AS A
ORDER BY TOT_ITEMS DESC LIMIT 1;


